export default {
  LIST_CHIP: [1, 5, 10, 25, 100, 500, 1000, 5000],
  API: {
    baseURL: 'https://colla-api-v2.playtime.work/api/',
    baseUrlImage: 'https://colla-api-v2.playtime.work/',
    // baseURL: 'https://colla-api.playtime.work/api/',
    // baseUrlImage: 'https://colla-api.playtime.work/',
    CheckPhone: 'auth/check-phone',
    VerifyPhone: 'auth/verify-phone',
    CheckAuth: 'auth/me',
    UpdateProfile: 'auth/profile',
    Product: 'product',
    Useraddress: 'useraddress',
    Order: 'order',
    SignInPhone: 'auth/signin-by-phone',
    SignUp: 'auth/signup',
    SignIn: 'auth/signin',
    SendOtp: 'auth/send-otp',
    VerifyOtp: 'auth/verify-otp',
    Cart: 'cart',
    ForgotPassword: 'auth/forgot-password',
    ResetPassword: 'auth/reset-password',
    Point: 'point',
    ImportProduct: 'import/product',
    ImportCart: 'import/cart',
    ImportOrder: 'import/order',
    UserCustomer: 'usercustomer',
    OnlineCart: 'online/cart',
    OnlineOrder: 'online/order',
    OnlineProduct: 'online/product',
    AgencyRequest: 'agencyrequest',
    UploadAvatar: 'auth/upload-avatar',
    Bank: 'bank',
    Device: 'device',
    Withdrawal: 'withdrawal',
    OfflineOrder: 'offline/order',
    OfflineProduct: 'offline/product',
    Recharge: 'recharge',
    Contact: 'contact',
  },
  RESPONSE_CODES: {
    SUCCESS: {
      SUCCESS: 200,
    },
    ERROR: {
      INTERNAL_SERVER: 500,
      NOT_FOUND: 404,
    },
  },
};
